baseURL = 'https://run-agent.jonnyzzz.com/'
languageCode = 'en-us'
title = 'run-agent.sh'

[module]
  [[module.imports]]
    path = "github.com/theNewDynamic/gohugo-theme-ananke/v2"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  description = 'Multi-Agent AI Orchestration for Software Development'
  author = 'Eugene Petrenko'
  github_repo = 'https://github.com/jonnyzzz/run-agent'
  site_logo = '/images/logo.png'
  featured_image = '/images/hero.png'
  background_color_class = 'bg-dark-blue'
  recent_posts_number = 0
